export const aboutFilmCopy = {
  en: {
    eyebrow: "A story, in our own words",
    title: "Meet the person behind Zuruny.",
    description: "Every story begins somewhere. Meet Zuruny’s founder and discover the love of Lebanon, its people, and its craft that brought this journey to life.",
    invitation: "Press play. Get to know us.",
    play: "Watch our story",
    playLabel: "Play the Zuruny story",
    filmLabel: "The story behind Zuruny, told by its founder",
    details: "1:24 · 9.6 MB · Sound on",
    data: "To save your data, this film loads only when you press play.",
    loading: "Loading film · 9.6 MB",
    error: "The film couldn’t load. Check your connection and try again.",
    retry: "Try again",
    replay: "Watch again",
    background: "At the potter’s wheel",
    pauseBackground: "Pause background",
    playBackground: "Play background",
  },
  fr: {
    eyebrow: "Une histoire, avec nos mots",
    title: "Une rencontre avec la fondatrice de Zuruny.",
    description: "Toute histoire a un point de départ. Rencontrez la fondatrice de Zuruny et découvrez l’amour du Liban, de ses habitants et de ses savoir-faire qui a donné vie à cette aventure.",
    invitation: "Lancez le film. Faisons connaissance.",
    play: "Voir notre histoire",
    playLabel: "Lancer le film Zuruny",
    filmLabel: "L’histoire de Zuruny, racontée par sa fondatrice",
    details: "1:24 · 9,6 Mo · Avec le son",
    data: "Pour économiser vos données, le film se charge uniquement à votre demande.",
    loading: "Chargement du film · 9,6 Mo",
    error: "Le film n’a pas pu se charger. Vérifiez votre connexion et réessayez.",
    retry: "Réessayer",
    replay: "Revoir le film",
    background: "Au tour du potier",
    pauseBackground: "Mettre le fond en pause",
    playBackground: "Animer le fond",
  },
};

export type AboutFilmCopy = (typeof aboutFilmCopy)[keyof typeof aboutFilmCopy];
